export const SEARCH_OPEN = 'SEARCH_OPEN';
export const MAIN_DRAWER_OPEN = 'MAIN_DRAWER_OPEN';
export const CART_DRAWER_OPEN = 'CART_DRAWER_OPEN';
export const SIDE_DRAWER_OPEN = 'SIDE_DRAWER_OPEN';
export const DASH_DRAWER_OPEN = 'DASH_DRAWER_OPEN';
export const DARK_MODE = 'DARK_MODE';
export const DASH_BOARD_ROUTES = 'DASH_BOARD_ROUTES';




//For Event
export const SLIDE_CHANGE = 'SLIDE_CHANGE';